discovery:
  apikey: _3kaJYEfvogkWFIu4BuC20vWtz7hCtR5xitybAzkllvJ
  url: https://api.us-south.discovery.watson.cloud.ibm.com/instances/e4e09f41-f328-4270-b876-f031bcc38f99
  date: 2019-04-30

# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/audit_check
    username: truongbn
    password: admin12345
    
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
      generate_statistics: true
      jdbc:
        batch_size: 20
        order_inserts: true
        order_updates: true

# logging
logging:
  level:
    root: INFO
